### ISSUE TITLE
Use of standard for sharing files

### ISSUE THREAD

**Issue by pierreozoux** [silexlabs/cloud-explorer#50]
You might be interested in this:

https://github.com/Decentralized-Sharing-Working-Group

And this:

https://remotestorage.io/

**Comment by zabojad** [comment]
Interesting indeed... But it seems quite new and not yet adopted widely enough to be something to support urgently, isn't it ?

**Comment by pierreozoux** [comment]
Yes, let's say it is the beginning. It was just a little hint. I'll close the issue for now. But the idea of remote storage is not new, and the aim was to create a standard for cloud storage. Even the javascript client gives an abstraction to GoogleDrive, dropbox or remote storage.

Actually remote storage is an equivalent to cloud-explorer.

**Comment by lexoyo** [comment]
But you know that @JbIPS has imlemented it in the new unifile version right?
