### ISSUE TITLE
docs and links to infilepicker

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/cloud-explorer#53]
Hello, just an info I wanted to share
https://www.inkfilepicker.com/ has become a scam website for casinos :(
The new website seems to be https://www.filepicker.com/ and the links to the docs have changed
We'll have to update the readme

**Comment by zabojad** [comment]
Damn ! Thanks for reporting it !

**Comment by zabojad** [comment]
4bc41b69f2b08c34d5a2545f620e7148f307160e update README with new File Picker website URL

**Comment by lexoyo** [comment]
Nice! Thank you :)
