### ISSUE TITLE
Demo.html error?

### ISSUE THREAD

**Issue by Sergio-Muriel** [silexlabs/cloud-explorer#56]
Hi,

I am trying to run the demo on my local environment, but all i got is a big black screen when clicking on the "Open" button:

Just build  the app with:
```
$ npm install
$ grunt
```

![step1](https://cloud.githubusercontent.com/assets/3207785/13053565/770958de-d405-11e5-9845-2031786c8cb2.png)
![step2](https://cloud.githubusercontent.com/assets/3207785/13053567/771d8f2a-d405-11e5-982e-d32a2506a9d5.png)

Note that:
- no explicit javascript error on the console.
Just a "options: null  onSuccess: <function>  onError: <function>"
- the request to http://cloud-explorer.herokuapp.com/api/1.0/services/list is done without errors.

any idea of what could be wrong?
Thank

**Comment by zabojad** [comment]
Hi there !

I have no idea why you get this...

Is your test case accessible anywhere online ?

**Comment by Sergio-Muriel** [comment]
So, on this server, i didn't get the back screen, but it doesn't work too.

https://tfeserver.be/_cloud-explorer/app/demo.html

**Comment by lexoyo** [comment]
Hi there 
In the online version, the iframe is still `display:none` but if you remove this rule by hand it displays the black rectangle like in your screen shot

**Comment by lexoyo** [comment]
hello,

i have made [these changes](https://github.com/silexlabs/cloud-explorer/pull/57) to
* have a fixed version of unifile in CE
* fix samples with latest unifile versions 

@zabojad I leave you here? the samples do work on my side now

**Comment by lexoyo** [comment]
Hi @Sergio-Muriel 
Did you have a chance to test my fixes?
On [your test page](http://tfeserver.be/_cloud-explorer/app/demo.html) it looks like it works? Only the CSS are not loaded?

**Comment by zabojad** [comment]
Hi there !

@Sergio-Muriel , we have two issues on [this page](http://tfeserver.be/_cloud-explorer/app/demo.html).

First as stated by @lexoyo, your cloud explorer css file is not loaded: ```GET http://tfeserver.be/_cloud-explorer/app/styles/cloud-explorer.css 404 (Not Found)```

Then, you cannot use the [cloud-explorer.herokuapp.com](http://cloud-explorer.herokuapp.com/api/1.0) unifile endpoint for your own instance of Cloud Explorer: 
```
demo.html:1 XMLHttpRequest cannot load http://cloud-explorer.herokuapp.com/api/1.0/services/list. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://tfeserver.be' is therefore not allowed access.
```
You have to implement your own instance of [unifile](https://github.com/silexlabs/unifile) that will allow via [CORS HTTP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) requests from the tfeserver.be domain...

**Comment by Sergio-Muriel** [comment]
Thanks for all your help. I think thats the problem yes.
