### ISSUE TITLE
Dropbox – The request to link the app is invalid

### ISSUE THREAD

**Issue by blues64** [silexlabs/cloud-explorer#62]
After "Logout all" button clicked, CE won't work with Dropbox and get error message "The request to link the app is invalid"

Let me share workaround I found.

---

Go to Dropbox.com
Click YourAccount -> Settings
in Security Tab, go Apps linked

delete " unifile, Silex Labs, Full Dropbox " by clicking X icon on the right side

Then Click "uninstall" 

restart browser (Edge on my case)

Go to silex editor 

You will see the page says "unifile would like access to the files and folders in your Dropbox"
Then Click "Allow"

Now Cloud Explorer works with Dropbox again

**Comment by lexoyo** [comment]
Thank you for the tip!
FYI we are about to start a webinar in french
https://twitter.com/silexlabs/status/765961740752457728
