### ISSUE TITLE
FTP error code : 450

### ISSUE THREAD

**Issue by blues64** [silexlabs/cloud-explorer#63]
After renew ftp session with another account credentials, previous folder or file list still remains the same.
Clicking any those folders or files will get error code : 450.

Repro issue:
- give ftp credentials to CE and start ftp session
- logout the session with "editor.silex.me/api/1.0/ftp/logout" to browser address bar
  (I have not tested "logout all" button due to issue #62)
- go back editor.silex.me and open CE
- give another ftp credentials to CE and looks ftp starting new session
- CE won't refresh folder or file list
- Clicking any of them will get error code : 450.

Any work around would be appreciated
Ciao

**Comment by singchan** [comment]
Hi
Did you try to reset your cookies? It should work

**Comment by blues64** [comment]
Oh! reset cookies works.
Thanks a lot
